### ISSUE TITLE
Adicionar Switch-case

### ISSUE THREAD

**Issue by arthurs159** [Figueiredoisaac/Calculadora-JAVA#1]
Oi Isaac, olhando seu projeto, vejo uma ótima oportunidade para utilizar o switch case, vejo que tem alguns ifs nessa parte do print abaixo e acredito que você consiga substituir pelo switch case.

![image](https://user-images.githubusercontent.com/77133022/195455304-0b640922-caf1-468b-b987-bea4c8bee7c2.png)

Qualquer dúvida, só me chamar, beleza?

**Comment by Figueiredoisaac** [comment]
Agradeço pelo feedback e pela dica @arthurs159 ! Aderi a sua sugestão e já fiz a alteração. Muito Obrigado!

![issue 01](https://user-images.githubusercontent.com/113912109/195989766-88c3278c-af0f-4865-8654-e73f89218b51.png)
